# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='标题', max_length=255)),
                ('content', models.TextField(help_text='正文')),
                ('style_type', models.IntegerField(choices=[(0, 'default')], default=0, help_text='样式类型')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
